const pool = require('../db');

const createTables = async () => {
  try {

    // Enable UUID generation (needed for UUID primary keys)
    await pool.query(`CREATE EXTENSION IF NOT EXISTS "uuid-ossp";`);

    // NOTE: PostGIS not required — using lat/lng decimals instead of GEOMETRY type

    // TABLE 1: users
    // Stores farmer/FPO manager accounts
    await pool.query(`
      CREATE TABLE IF NOT EXISTS users (
        id                UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
        name              TEXT,
        phone             TEXT UNIQUE NOT NULL,
        role              TEXT DEFAULT 'farmer' CHECK (role IN ('farmer', 'fpo_manager', 'admin')),
        language          TEXT DEFAULT 'hi',
        district          TEXT,
        state             TEXT,
        created_at        TIMESTAMP DEFAULT NOW()
      );
    `);

    // Add FPO credential columns (safe to run on every startup)
    await pool.query(`ALTER TABLE users ADD COLUMN IF NOT EXISTS fpo_username TEXT UNIQUE;`);
    await pool.query(`ALTER TABLE users ADD COLUMN IF NOT EXISTS fpo_password_hash TEXT;`);
    console.log('✅ Table created/updated: users');

    // TABLE 2: farms
    // Each user can have multiple farms
    await pool.query(`
      CREATE TABLE IF NOT EXISTS farms (
        id          UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
        user_id     UUID REFERENCES users(id) ON DELETE CASCADE,
        farm_name   TEXT,
        size_acres  DECIMAL,
        district    TEXT,
        state       TEXT,
        latitude    DECIMAL,
        longitude   DECIMAL,
        created_at  TIMESTAMP DEFAULT NOW()
      );
    `);
    console.log('✅ Table created: farms');

    // TABLE 3: soil_scans
    // Each scan stores all nutrient values and which method was used
    await pool.query(`
      CREATE TABLE IF NOT EXISTS soil_scans (
        id              UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
        farm_id         UUID REFERENCES farms(id) ON DELETE CASCADE,
        input_method    TEXT CHECK (input_method IN ('ocr', 'manual')),
        ph              DECIMAL,
        nitrogen        DECIMAL,
        phosphorus      DECIMAL,
        potassium       DECIMAL,
        organic_carbon  DECIMAL,
        zinc            DECIMAL,
        sulfur          DECIMAL,
        iron            DECIMAL,
        crop            TEXT,
        sowing_date     DATE,
        scanned_at      TIMESTAMP DEFAULT NOW()
      );
    `);
    console.log('✅ Table created: soil_scans');

    // TABLE 4: advisories
    // Stores the fertilizer recommendation generated by the rule engine
    await pool.query(`
      CREATE TABLE IF NOT EXISTS advisories (
        id                  UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
        scan_id             UUID REFERENCES soil_scans(id) ON DELETE CASCADE,
        recommendations     JSONB,
        soil_health_score   INTEGER,
        total_cost          DECIMAL,
        language            TEXT DEFAULT 'hi',
        generated_at        TIMESTAMP DEFAULT NOW()
      );
    `);
    console.log('✅ Table created: advisories');

    // TABLE 5: crop_calendar
    // Each event in a farmer's crop season timeline
    await pool.query(`
      CREATE TABLE IF NOT EXISTS crop_calendar (
        id              UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
        scan_id         UUID REFERENCES soil_scans(id) ON DELETE CASCADE,
        event_date      DATE,
        event_label     TEXT,
        event_label_hi  TEXT,
        reminder_sent   BOOLEAN DEFAULT false
      );
    `);
    console.log('✅ Table created: crop_calendar');

    // TABLE 6: fpo_members
    // Maps which farms belong to which FPO (Farmer Producer Organisation)
    await pool.query(`
      CREATE TABLE IF NOT EXISTS fpo_members (
        id          UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
        fpo_id      UUID NOT NULL,
        farm_id     UUID REFERENCES farms(id) ON DELETE CASCADE,
        joined_at   TIMESTAMP DEFAULT NOW()
      );
    `);
    console.log('✅ Table created: fpo_members');

    console.log('\n🎉 All 6 tables created successfully!');

  } catch (err) {
    console.error('❌ Error creating tables:', err.message);
  }
  // NOTE: Do NOT call pool.end() here — the pool is shared across the whole app
};

module.exports = { createTables };
